name: Test

on: [pull_request] #tmp for testing w/o merge

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"] #3.12 breaks due to snapshottest
        os: [ubuntu-latest, windows-latest, macos-13] # add macos-14 once nlopt issue is solved
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Disable JIT on Windows
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export NUMBA_DISABLE_JIT=1
          fi
        shell: bash
      - name: Run tox with python on PATH
        run: tox -e py